version: 2
updates:
- package-ecosystem: nuget
  directory: "/Module"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/PSWordCloud.Tests"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
